<a href="https://colab.research.google.com/github/punramon/python_dataviz2024/blob/main/Data_Viz_2024_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ให้หา
1. ความแตกต่างของ ค่าเฉลี่ย ของข้อมูล Chlo_a ทุกๆ station ระหว่างปี 2018 และ ปี 2019

2. สร้างตารางค่าเฉลี่ย Chlo_b ทุกๆ station ของแต่ละเดือน

### 1. ความแตกต่างของ ค่าเฉลี่ย ของข้อมูล Chlo_a ทุกๆ station ระหว่างปี 2018 และ ปี 2019

In [26]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

path = '/content/drive/MyDrive/Examdv' #set path --> folder and then join path เพื่อให้โค้ดrunได้ทุกที่

tidydata_file_path = os.path.join(path,'test-TidyData_2024.xlsx')
print(tidydata_file_path)

/content/drive/MyDrive/Examdv/test-TidyData_2024.xlsx

In [4]:
tidydata = pd.read_excel(tidydata_file_path)
tidydata

,month,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell,@dropdown
0,July_2018,1,1,0.094645,0.011954,0.026780,30.2,5.54,622.7,330.3,545.2,4.37,0.172902,0.052817,0.012748,1.635833e+05,NaN
1,July_2018,2,1,0.038433,0.059019,0.021387,29.1,6.24,580.7,307.0,488.2,6.55,0.154197,0.144843,0.006086,1.166667e+06,NaN
2,July_2018,3,1,0.043884,0.089415,0.023223,29.7,5.52,547.1,289.4,462.2,5.67,0.153097,0.154321,0.014158,2.970000e+06,NaN
3,July_2018,4,1,0.039836,0.064552,0.016537,29.2,5.92,473.6,249.2,397.9,0.69,0.157026,0.387408,0.056951,5.066667e+05,NaN
4,July_2018,5,1,0.044712,0.062424,0.022990,29.5,5.79,685.5,366.0,581.2,4.46,0.204024,0.043387,0.007239,1.265000e+06,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,July_2019,2,3,0.030521,0.015358,0.018067,31.2,7.74,580.5,309.2,517.0,6.31,0.132034,0.030959,-0.000064,2.665833e+05,NaN
194,July_2019,3,3,0.024081,0.020217,0.015981,29.7,7.50,513.0,272.6,436.0,3.00,0.230116,0.059103,-0.000064,6.428333e+05,NaN
195,July_2019,4,3,0.015525,0.009612,0.009373,31.5,7.51,550.9,289.8,498.4,4.02,0.123546,0.136428,-0.000064,2.945000e+05,NaN
196,July_2019,5,3,0.015180,0.011811,0.009697,28.5,7.31,540.6,287.4,443.4,1.53,0.110028,0.056057,-0.000064,3.470833e+05,NaN
197,July_2019,6,3,0.008556,0.010605,0.005704,31.5,7.71,544.7,288.2,493.8,6.32,0.165042,0.105817,-0.000064,3.692500e+05,NaN

In [5]:
# ตัด column '@dropdown' ออก
tidydata = tidydata.drop('@dropdown', axis=1)
tidydata

,month,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell
0,July_2018,1,1,0.094645,0.011954,0.026780,30.2,5.54,622.7,330.3,545.2,4.37,0.172902,0.052817,0.012748,1.635833e+05
1,July_2018,2,1,0.038433,0.059019,0.021387,29.1,6.24,580.7,307.0,488.2,6.55,0.154197,0.144843,0.006086,1.166667e+06
2,July_2018,3,1,0.043884,0.089415,0.023223,29.7,5.52,547.1,289.4,462.2,5.67,0.153097,0.154321,0.014158,2.970000e+06
3,July_2018,4,1,0.039836,0.064552,0.016537,29.2,5.92,473.6,249.2,397.9,0.69,0.157026,0.387408,0.056951,5.066667e+05
4,July_2018,5,1,0.044712,0.062424,0.022990,29.5,5.79,685.5,366.0,581.2,4.46,0.204024,0.043387,0.007239,1.265000e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,July_2019,2,3,0.030521,0.015358,0.018067,31.2,7.74,580.5,309.2,517.0,6.31,0.132034,0.030959,-0.000064,2.665833e+05
194,July_2019,3,3,0.024081,0.020217,0.015981,29.7,7.50,513.0,272.6,436.0,3.00,0.230116,0.059103,-0.000064,6.428333e+05
195,July_2019,4,3,0.015525,0.009612,0.009373,31.5,7.51,550.9,289.8,498.4,4.02,0.123546,0.136428,-0.000064,2.945000e+05
196,July_2019,5,3,0.015180,0.011811,0.009697,28.5,7.31,540.6,287.4,443.4,1.53,0.110028,0.056057,-0.000064,3.470833e+05
197,July_2019,6,3,0.008556,0.010605,0.005704,31.5,7.71,544.7,288.2,493.8,6.32,0.165042,0.105817,-0.000064,3.692500e+05

In [6]:
# prompt: ให้แบ่งค่าในcolumn month โดยใช้ _ แบ่ง แล้วเอาค่าตัวเลขที่ถูกแบ่งสร้างเป็น column Year ลบ month เดิมออก

# แบ่งค่าใน column 'month' และสร้าง column 'Year'
tidydata[['Month', 'Year']] = tidydata['month'].str.split('_',expand=True)

# ลบ column 'month' เดิม
tidydata = tidydata.drop('month', axis=1)

# แสดง DataFrame ที่อัปเดตแล้ว
tidydata

,station,rep.,Chlo_a,Chlo_b,total_Caro,Temp.,pH,EC,Salinity,TDS,DO,Nitrate,Ammonium,Phosphate,No.Algal_cell,Month,Year
0,1,1,0.094645,0.011954,0.026780,30.2,5.54,622.7,330.3,545.2,4.37,0.172902,0.052817,0.012748,1.635833e+05,July,2018
1,2,1,0.038433,0.059019,0.021387,29.1,6.24,580.7,307.0,488.2,6.55,0.154197,0.144843,0.006086,1.166667e+06,July,2018
2,3,1,0.043884,0.089415,0.023223,29.7,5.52,547.1,289.4,462.2,5.67,0.153097,0.154321,0.014158,2.970000e+06,July,2018
3,4,1,0.039836,0.064552,0.016537,29.2,5.92,473.6,249.2,397.9,0.69,0.157026,0.387408,0.056951,5.066667e+05,July,2018
4,5,1,0.044712,0.062424,0.022990,29.5,5.79,685.5,366.0,581.2,4.46,0.204024,0.043387,0.007239,1.265000e+06,July,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,2,3,0.030521,0.015358,0.018067,31.2,7.74,580.5,309.2,517.0,6.31,0.132034,0.030959,-0.000064,2.665833e+05,July,2019
194,3,3,0.024081,0.020217,0.015981,29.7,7.50,513.0,272.6,436.0,3.00,0.230116,0.059103,-0.000064,6.428333e+05,July,2019
195,4,3,0.015525,0.009612,0.009373,31.5,7.51,550.9,289.8,498.4,4.02,0.123546,0.136428,-0.000064,2.945000e+05,July,2019
196,5,3,0.015180,0.011811,0.009697,28.5,7.31,540.6,287.4,443.4,1.53,0.110028,0.056057,-0.000064,3.470833e+05,July,2019
197,6,3,0.008556,0.010605,0.005704,31.5,7.71,544.7,288.2,493.8,6.32,0.165042,0.105817,-0.000064,3.692500e+05,July,2019

In [47]:
# prompt: ให้หาความแตกต่างของ ค่าเฉลี่ย ของข้อมูล Chlo_a ทุกๆ station ระหว่างปี 2018 และ ปี 2019

# คำนวณค่าเฉลี่ย Chlo_a สำหรับแต่ละ station ในปี 2018
chlo_a_2018 = tidydata[tidydata['Year'] == '2018'].groupby('station')['Chlo_a'].mean()

# คำนวณค่าเฉลี่ย Chlo_a สำหรับแต่ละ station ในปี 2019
chlo_a_2019 = tidydata[tidydata['Year'] == '2019'].groupby('station')['Chlo_a'].mean()

# คำนวณความแตกต่างของค่าเฉลี่ยระหว่างปี 2018 และ 2019
difference = chlo_a_2019 - chlo_a_2018

# แสดงผลลัพธ์
print("ค่าเฉลี่ย Chlo_a ทุกๆ station ระหว่างปี 2018 และ 2019:")
print(difference)

ค่าเฉลี่ย Chlo_a ทุกๆ station ระหว่างปี 2018 และ 2019:
station
1   -0.034261
2   -0.020201
3   -0.030228
4   -0.025173
5   -0.023331
6   -0.028215
Name: Chlo_a, dtype: float64

In [9]:
chlo_a_2018

station
1    0.052529
2    0.048112
3    0.053285
4    0.046794
5    0.043432
6    0.043809
Name: Chlo_a, dtype: float64

In [10]:
chlo_a_2019

station
1    0.018268
2    0.027911
3    0.023057
4    0.021620
5    0.020100
6    0.015594
Name: Chlo_a, dtype: float64

In [12]:
difference

station
1   -0.034261
2   -0.020201
3   -0.030228
4   -0.025173
5   -0.023331
6   -0.028215
Name: Chlo_a, dtype: float64

In [49]:
# prompt: รวมตาราง chlo_a_2018 chlo_a_2019 และ difference
# รวมตาราง chlo_a_2018, chlo_a_2019 และ difference
result = pd.concat([chlo_a_2018, chlo_a_2019, difference], axis=1)
result.columns = ['Chlo_a_2018', 'Chlo_a_2019', 'Difference']
result

         Chlo_a_2018  Chlo_a_2019  Difference
station
1           0.052529     0.018268   -0.034261
2           0.048112     0.027911   -0.020201
3           0.053285     0.023057   -0.030228
4           0.046794     0.021620   -0.025173
5           0.043432     0.020100   -0.023331
6           0.043809     0.015594   -0.028215



---

### 2. สร้างตารางค่าเฉลี่ย Chlo_b ทุกๆ station ของแต่ละเดือน

In [51]:
# prompt: สร้างตารางค่าเฉลี่ย Chlo_b ทุกๆ station ของแต่ละเดือน

# สร้างตารางค่าเฉลี่ย Chlo_b ทุกๆ station ของแต่ละเดือน
chlo_b_mean = tidydata.groupby(['Month', 'station'])['Chlo_b'].mean().reset_index()
chlo_b_mean

   Month  station    Chlo_b
0    Apr        1  0.051381
1    Apr        2  0.019378
2    Apr        3  0.030775
3    Apr        4  0.020170
4    Apr        5  0.027015
5    Apr        6  0.025655
6    Aug        1  0.075665
7    Aug        2  0.065403
8    Aug        3  0.065179
9    Aug        4  0.061289
10   Aug        5  0.060107
11   Aug        6  0.063027
12   Dec        1  0.070061
13   Dec        2  0.064375
14   Dec        3  0.080867
15   Dec        4  0.061951
16   Dec        5  0.070085
17   Dec        6  0.065663
18   Jan        1  0.022451
19   Jan        2  0.014968
20   Jan        3  0.017722
21   Jan        4  0.012142
22   Jan        5  0.009789
23   Jan        6  0.013856
24  July        1  0.030526
25  July        2  0.038211
26  July        3  0.045500
27  July        4  0.035326
28  July        5  0.037839
29  July        6  0.033133
30  June        1  0.020548
31  June        2  0.013194
32  June        3  0.013301
33  June        4  0.013821
34  June        5  0.013880
35  June        6  0.008583
36   May        1  0.015949
37   May        2  0.028765
38   May        3  0.015890
39   May        4  0.015559
40   May        5  0.016623
41   May        6  0.023882
42   Nov        1  0.075937
43   Nov        2  0.064552
44   Nov        3  0.097963
45   Nov        4  0.070605
46   Nov        5  0.063866
47   Nov        6  0.073360
48   Oct        1  0.131764
49   Oct        2  0.122767
50   Oct        3  0.106404
51   Oct        4  0.090834
52   Oct        5  0.082381
53   Oct        6  0.079449
54   Sep        1  0.063890
55   Sep        2  0.074578
56   Sep        3  0.076292
57   Sep        4  0.064670
58   Sep        5  0.060733
59   Sep        6  0.061750

In [52]:
# แปลงรูปแบบเป็น wide format
chlo_b_mean_pivot = chlo_b_mean.pivot(index=['station'], columns='Month', values='Chlo_b')
chlo_b_mean_pivot

Month,Apr,Aug,Dec,Jan,July,June,May,Nov,Oct,Sep
station,,,,,,,,,,
1,0.051381,0.075665,0.070061,0.022451,0.030526,0.020548,0.015949,0.075937,0.131764,0.063890
2,0.019378,0.065403,0.064375,0.014968,0.038211,0.013194,0.028765,0.064552,0.122767,0.074578
3,0.030775,0.065179,0.080867,0.017722,0.045500,0.013301,0.015890,0.097963,0.106404,0.076292
4,0.020170,0.061289,0.061951,0.012142,0.035326,0.013821,0.015559,0.070605,0.090834,0.064670
5,0.027015,0.060107,0.070085,0.009789,0.037839,0.013880,0.016623,0.063866,0.082381,0.060733
6,0.025655,0.063027,0.065663,0.013856,0.033133,0.008583,0.023882,0.073360,0.079449,0.061750

In [53]:
# แสดงตาราง
from google.colab import data_table
data_table.DataTable(chlo_b_mean_pivot, include_index=True, num_rows_per_page=6)



---